export const PRODUCT_MAIN_BANNER_REQUEST = 'PRODUCT_MAIN_BANNER_REQUEST';
export const PRODUCT_MAIN_BANNER_SUCCESS = 'PRODUCT_MAIN_BANNER_SUCCESS';
export const PRODUCT_MAIN_BANNER_FAIL = 'PRODUCT_MAIN_BANNER_FAIL';